name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Heroku CLI
        uses: akhileshns/setup-heroku@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku App
        run: |
          heroku apps:create flask-chatbot-demo || true
          heroku git:remote -a flask-chatbot-demo

      - name: Set environment variables
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set \
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            FLASK_DEBUG=0 \
            BACKEND_URL=https://your-backend-api.com/ask \
            -a flask-chatbot-demo

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "flask-chatbot-demo"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          dontuseforce: 1
          healthcheck: "https://flask-chatbot-demo.herokuapp.com/health"
          env_file: ".env"